### PR TITLE
Enable WebRTC

### PR DESCRIPTION
**Pull request by hiten247**

### CODE REVIEW

**Comment by dbuechel** [comment]
Enabling WebRTC breaks the low-level input monitoring of SEB, as already discussed in issue #3. I thus have to reject and close this pull request.

**Comment by hiten247** [comment]
Are you referring to the keyboard shortcuts? As of the latest code with WebRTC enabled, the keyboard shortcuts seem to work fine.

**Comment by chrisaut** [comment]
@dbuechel in #3 you state:

"There indeed is a flag to enable WebRTC functionality ("enable-media-stream"), it however has severe side effects. It namely completely breaks the keyboard monitoring and all custom keyboard shortcuts of SEB (e.g. CTRL+Q to quit). It strangely only happens once I visit the test site you specified, but I don't think it is an issue with the site, rather an upstream problem in the browser engine once the WebRTC functionality is initialized."

At least the CTRL+Q shortcut seems to still work, even while the camera test is running on https://test.webrtc.org/
I have also tested it on our internal software that does WebRTC things. Is there another scenario that this breaks, something we should test for? If not, could you give this another test and reconsider?

Thanks

**Comment by dbuechel** [comment]
You are right! The last time I checked, it used to be that the complete input monitoring of keyboard and mouse stopped working (e.g. CTRL+Q to quit or WIN+A for the action center as well as all suppression of keyboard or mouse input).

I will update the browser engine to the latest version and check whether it still works and in the meantime discuss with our team how we will proceed. We need to make sure that this works reliable in CEF / CefSharp and that it isn't just some temporary coincidence, as we now already integrated the new WebView2 for the remote proctoring functionality in version 3.2.

I'll update issue #3 and suggest that we continue the discussion there.

**Pull request closed without merging**
